mybatis:
  mapper-locations: classpath:/repository/**/*.xml
  type-aliases-package: com.refsys.adminweb.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis.spring.mapper: DEBUG
    org.apache.ibatis: DEBUG
    com.example.project.mapper: DEBUG

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/admin
    driver-class-name: org.h2.Driver
    username: sa
    password: